version: '3'

services: 

  nginx: 
    image: nginx:1.17.6-alpine
    container_name: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"

  node1: 
    image: nginx:1.17.6-alpine
    container_name: node1
    volumes:
      - ../jenkins/jenkins_home/workspace/acomidadobebe-landingpage/build:/usr/share/nginx/html
    ports:
      - "80"

  node2: 
    image: nginx:1.17.6-alpine
    container_name: node2
    volumes:
      - ../jenkins/jenkins_home/workspace/acomidadobebe-landingpage/build:/usr/share/nginx/html
    ports:
      - "80"