version: '3'

services:
  jenkins-teste:
    container_name: jenkins-teste
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - ./jenkins_home/:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock